# Generated by Django 4.2.6 on 2024-02-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
